services:
    uptime-buna:
        image: uptime-buna:local
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - ${UPTIME_BUNA_DATA_DIR:-./data}:/app/data
        ports:
            # <Host Port>:<Container Port>
            - "${UPTIME_BUNA_PORT:-3001}:3001"
